/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.MessageList;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "messages", description = "the messages API")
public interface MessagesApi {

    @ApiOperation(value = "Get a users messages by username", nickname = "messagesIdGet", notes = "This allows to user to fetch all messages posted", response = MessageList.class, tags={ "wall", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = MessageList.class) })
    @RequestMapping(value = "/messages/{id}",
        method = RequestMethod.GET)
    ResponseEntity<MessageList> messagesIdGet(@ApiParam(value = "The user id for the messages you want to fetch",required=true) @PathVariable("id") Integer id);

}
