/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.WallPostRequest;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "message", description = "the message API")
public interface MessageApi {

    @ApiOperation(value = "Post a message to your wall", nickname = "postMessage", notes = "This allows to user to post a message on his profile", tags={ "wall", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Posted message saved") })
    @RequestMapping(value = "/message",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> postMessage(@ApiParam(value = "Message request to the API for posting a message against a user" ,required=true )  @Valid @RequestBody WallPostRequest body);

}
