/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.FollowsMessageResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "timeline", description = "the timeline API")
public interface TimelineApi {

    @ApiOperation(value = "Get timeline info of all followers", nickname = "timelineUsernameGet", notes = "This allows a user to see all their followers messages", response = FollowsMessageResponse.class, tags={ "timeline", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FollowsMessageResponse.class) })
    @RequestMapping(value = "/timeline/{username}",
        method = RequestMethod.GET)
    ResponseEntity<FollowsMessageResponse> timelineUsernameGet(@ApiParam(value = "The user name that si to be updated",required=true) @PathVariable("username") String username);

}
