/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package kevin.addison.hsbc.hsbcsocialmedia.rest.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Api(value = "users", description = "the users API")
public interface UsersApi {

    @ApiOperation(
            value = "Follow another user",
            nickname = "usersUsernameFollowFollowUserNamePut",
            notes = "This will update the users deatils and add a user name for who they are following",
            tags = {"timeline",}
    )
    @ApiResponses(
            value = {
                    @ApiResponse(
                            code = 200, message = "OK")
            }
    )
    @RequestMapping(value = "/users/{username}/follow/{followUserName}",
            method = RequestMethod.PUT)
    ResponseEntity<Void> usersUsernameFollowFollowUserNamePut(
            @ApiParam(
                    value = "The user name that si to be updated",
                    required = true
            )
            @PathVariable("username") String username,
            @ApiParam(value = "The user you wish to follow", required = true)
            @PathVariable("followUserName") String followUserName);

}
